clickhouse:
  image:
    repository: clickhouse/clickhouse-server
    tag: head-alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  persistence:
    hotStorage:
      mountPath: /var/lib/clickhouse/hot-storage
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    coldStorage:
      mountPath: /var/lib/clickhouse/cold-storage
      accessModes:
        - ReadWriteOnce
      size: 10Gi

  service:
    type: LoadBalancer
    ports:
      http: 8123
      rpc: 9000
      replication: 9009
  client:
    enabled: true
