clickhouse:
  image:
    repository: clickhouse/clickhouse-server
    tag: head-alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  hotStorage: "5Gi"
  coldStorage: "10Gi"
  moveFactor: 0.2
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  service:
    type: NodePort # Change service type to NodePort
    ports:
      http: 8123
      rpc: 9000
      replication: 9009
  client:
    enabled: true 