clickhouse:
  image:
    repository: clickhouse/clickhouse-server
    tag: head-alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  hotConfiguration:
    path: "/var/lib/clickhouse/hot-storage"
    size: "10Gi"
  coldConfiguration:
    path: "/var/lib/clickhouse/cold-storage"
    size: "20Gi"
    moveFactor: 0.2
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 2
      memory: 8Gi
  service:
    type: LoadBalancer
    ports:
      http: 8123
      rpc: 9000
      replication: 9009
  client:
    enabled: true
