apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-clickhouse-client
spec:
  containers:
  - name: clickhouse-client
    image: yandex/clickhouse-client:latest
    command: ["tail", "-f", "/dev/null"]
    env:
    - name: CLICKHOUSE_HOST
      value: "clickhouse-clickhouse"
    - name: CLICKHOUSE_PORT
      value: "8123"
