apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  storage_configuration.xml: |
    <?xml version="1.0"?>
    <yandex>
      <storage_configuration>
        <disks>
          <hot_disk>
            <type>local</type>
            <path>{{ .Values.clickhouse.hotConfiguration.path }}</path>
          </hot_disk>
          <cold_disk>
            <type>local</type>
            <path>{{ .Values.clickhouse.coldConfiguration.path }}</path>
          </cold_disk>
        </disks>

        <policies>
          <hot_cold>
            <volumes>
              <hot>
                <disk>hot_disk</disk>
              </hot>
              <cold>
                <disk>cold_disk</disk>
              </cold>
            </volumes>
            <move_factor>{{ .Values.clickhouse.coldConfiguration.moveFactor }}</move_factor>
          </hot_cold>
        </policies>
      </storage_configuration>
    </yandex>
