apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  storage_configuration.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <storage_configuration>
        <disks>
          <hot_disk>
            <type>local</type>
            <path>{{ .Values.clickhouse.persistence.hotStorage.mountPath }}</path>
          </hot_disk>
          <cold_disk>
            <type>local</type>
            <path>{{ .Values.clickhouse.persistence.coldStorage.mountPath }}</path>
          </cold_disk>
        </disks>

        <policies>
          <default>
          <move_factor>0.2</move_factor>
            <volumes>
              <hot>
                <disk>hot_disk</disk>
              </hot>
              <cold>
                <disk>cold_disk</disk>
              </cold>
            </volumes>
          </default>
        </policies>
      </storage_configuration>
    </clickhouse>
