apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    app: clickhouse
spec:
  replicas: {{ .Values.clickhouse.replicaCount }}
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.clickhouse.resources.limits.cpu }}
              memory: {{ .Values.clickhouse.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clickhouse.resources.requests.cpu }}
              memory: {{ .Values.clickhouse.resources.requests.memory }}
          env:
            - name: ENABLE_PART_LOG
              value: "1"
          ports:
            - containerPort: {{ .Values.clickhouse.service.ports.http }}
              name: http
            - containerPort: {{ .Values.clickhouse.service.ports.rpc }}
              name: rpc
            - containerPort: {{ .Values.clickhouse.service.ports.replication }}
              name: replication
          volumeMounts:
            - name: hot-storage
              mountPath: {{ .Values.clickhouse.persistence.hotStorage.mountPath }}
            - name: cold-storage
              mountPath: {{ .Values.clickhouse.persistence.coldStorage.mountPath }}
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/storage_configuration.xml
      volumes:
        - name: hot-storage
          emptyDir: {}
        - name: cold-storage
          emptyDir: {}
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
